# Generated by Django 5.0.6 on 2026-05-23 16:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.PositiveIntegerField(editable=False)),
                ('total_rent', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('owner_earning', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('confirmed', 'Dikonfirmasi Penyedia'), ('paid', 'Sudah Dibayar'), ('active', 'Sedang Berlangsung'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan'), ('rejected', 'Ditolak Penyedia')], default='pending', max_length=20)),
                ('deposit_returned', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('active_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrowed_transactions', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Transaksi',
                'verbose_name_plural': 'Transaksi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('qris', 'QRIS'), ('transfer', 'Transfer Bank')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('success', 'Berhasil'), ('failed', 'Gagal')], default='pending', max_length=20)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('is_reported', models.BooleanField(default=False)),
                ('report_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Ulasan',
                'verbose_name_plural': 'Ulasan',
                'ordering': ['-created_at'],
                'unique_together': {('transaction', 'reviewer')},
            },
        ),
    ]
