# Generated by Django 5.0.6 on 2026-05-23 16:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('borrow_request', 'Pengajuan Peminjaman'), ('confirmed', 'Pengajuan Dikonfirmasi'), ('rejected', 'Pengajuan Ditolak'), ('payment_received', 'Pembayaran Diterima'), ('item_picked_up', 'Barang Diambil'), ('return_reminder', 'Pengingat Pengembalian'), ('item_returned', 'Barang Dikembalikan'), ('completed', 'Transaksi Selesai'), ('deposit_returned', 'Deposit Dikembalikan'), ('cancelled', 'Transaksi Dibatalkan'), ('late_return', 'Keterlambatan Pengembalian')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'ordering': ['-created_at'],
            },
        ),
    ]
